// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lytqacjmoclgtrxmherf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5dHFhY2ptb2NsZ3RyeG1oZXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjM3ODUsImV4cCI6MjA2NTkzOTc4NX0.M2MSR_QpCvYVIJk92rEavYxiol4d-7F8z2_WZqpVzvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);